# Copyright 2013, The Toft Authors.
# All rights reserved.
#
# Author: CHEN Feng <chen3feng@gmail.com>

proto_library(
    name = 'message_proto',
    srcs = 'message.proto',
    deps = ':option_proto'
)

proto_library(
    name = 'error_code_proto',
    srcs = 'error_code.proto'
)

proto_library(
    name = 'option_proto',
    srcs = 'option.proto'
)

proto_library(
    name = 'meta_proto',
    srcs = 'meta.proto',
    deps = ':option_proto'
)


